main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('pokemon/', views.pokemon_index, name='index'),
  path('pokemon/<int:poke_id>/', views.pokemon_detail, name='detail'),
  path('pokemon/create/', views.PokemonCreate.as_view(), name='pokemon_create'),
  path('pokemon/<int:pk>/update/', views.PokemonUpdate.as_view(), name='pokemon_update'),
  path('pokemon/<int:pk>/delete/', views.PokemonDelete.as_view(), name='pokemon_delete'),
  path('pokemon/<int:poke_id>/add_training/', views.add_training, name='add_training'),
  path('pokemon/<int:poke_id>/assoc_item/<int:item_id>/', views.assoc_item, name='assoc_item'),
  path('pokemon/<int:poke_id>/unassoc_item/<int:item_id>/', views.unassoc_item, name='unassoc_item'),
  path('items/', views.ItemList.as_view(), name='items_index'),
  path('items/<int:pk>/', views.ItemDetail.as_view(), name='items_detail'),
  path('items/create/', views.ItemCreate.as_view(), name='items_create'),
  path('items/<int:pk>/update/', views.ItemUpdate.as_view(), name='items_update'),
  path('items/<int:pk>/delete/', views.ItemDelete.as_view(), name='items_delete'),
]

pokemoncollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

REGIONS = (
    ('H', 'Hoenn'),
    ('K', 'Kanto'),
    ('J', 'Johto')
)

class Item(models.Model):
  name = models.CharField(max_length=50)
  types = models.CharField(max_length=20)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('items_detail', kwargs={'pk': self.id})

class Pokemon(models.Model):
  name = models.CharField(max_length=100)
  breed = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  age = models.IntegerField()
  items = models.ManyToManyField(Item)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('detail', kwargs={'poke_id': self.id})

class Training(models.Model):
  date = models.DateField('training date')
  region = models.CharField(
    max_length=1,
    choices=REGIONS,
    default=REGIONS[0][0]
  )
  pokemon = models.ForeignKey(Pokemon, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_region_display()} on {self.date}"

  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Training

class TrainingForm(ModelForm):
  class Meta:
    model = Training
    fields = ['date', 'region']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Pokemon, Item
from .forms import TrainingForm

class PokemonCreate(CreateView):
  model = Pokemon
  fields = ['name', 'breed', 'description', 'age']

class PokemonUpdate(UpdateView):
  model = Pokemon
  fields = ['breed', 'description', 'age']

class PokemonDelete(DeleteView):
  model = Pokemon
  success_url = '/pokemon/'

def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def pokemon_index(request):
  pokemon = Pokemon.objects.all()
  return render(request, 'pokemon/index.html', { 'pokemon': pokemon })

def pokemon_detail(request, poke_id):
  poke = Pokemon.objects.get(id=poke_id)
  items_pokemon_doesnt_have = Item.objects.exclude(id__in = poke.items.all().values_list('id'))
  training_form = TrainingForm()
  return render(request, 'pokemon/detail.html', {
    'poke': poke, 'training_form': training_form,
    'items': items_pokemon_doesnt_have
  })

def add_training(request, poke_id):
  form = TrainingForm(request.POST)
  if form.is_valid():
    new_training = form.save(commit=False)
    new_training.poke_id = poke_id
    new_training.save()
  return redirect('detail', poke_id=poke_id)


def assoc_item(request, poke_id, item_id):
  Pokemon.objects.get(id=poke_id).items.add(item_id)
  return redirect('detail', poke_id=poke_id)

def unassoc_item(request, poke_id, item_id):
  Pokemon.objects.get(id=poke_id).items.remove(item_id)
  return redirect('detail', poke_id=poke_id)

class ItemList(ListView):
  model = Item

class ItemDetail(DetailView):
  model = Item

class ItemCreate(CreateView):
  model = Item
  fields = '__all__'

class ItemUpdate(UpdateView):
  model = Item
  fields = ['name', 'type']

class ItemDelete(DeleteView):
  model = Item
  success_url = '/items/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Pokemon Collector</h1>
<hr />
<p>Catch 'em all!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Pokemon Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
  <header class="navbar-fixed">
    <nav>
        
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Pokemon Collector</a></li>
        </ul>
        
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'items_create' %}">Add an Item</a></li>
            <li><a href="{% url 'items_index' %}">View All Items</a></li>
            <li><a href="{% url 'pokemon_create' %}">Add a Pokemon</a></li>
            <li><a href="{% url 'index' %}">View All My Pokemon</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2020 Pokemon Collector &nbsp;</div>
  </footer>
</body>

</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/item_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Item</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'items_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/item_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Item Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ item.name }}</span>
        <p>Type: {{ item.types }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'items_update' item.id %}">Edit</a>
        <a href="{% url 'items_delete' item.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/item_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Item</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/item_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Item List</h1>

{% for item in item_list %}
  <a href="{% url 'items_detail' item.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ item.name }}</span>
            <p>Type: {{ item.types }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/pokemon_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Pokemon</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' pokemon.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/pokemon_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Pokemon</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/pokemon/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Pokemon Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ poke.name }}</span>
        <p>Breed: {{ poke.breed }}</p>
        <p>Description: {{ poke.description }}</p>
        {% if poke.age > 0 %}
          <p>Age: {{ poke.age }}</p>
        {% else %}
          <p>Age: Kitten</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'pokemon_update' poke.id %}">Edit</a>
        <a href="{% url 'pokemon_delete' poke.id %}">Delete</a>
      </div>
    </div>
  <div class="col s6">
    <form action="{% url 'add_training' poke.id %}" method="post">
      {% csrf_token %}
      {{ training_form.as_p }}
      <input type="submit" class="btn" value="Add Training">
    </form>
    <br>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Region</th></tr>
      </thead>
      <tbody>
        {% for training in poke.training_set.all %}
          <tr>
            <td>{{training.date}}</td>
            <td>{{training.get_region_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ poke.name }}'s Items</h3>
    {% if poke.items.count %}
      {% for item in poke.items.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="types: {{ item.types }}">{{ item.types }}</span> {{ item.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_item' poke.id item.id %}" method="post">
                {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Items</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Items</h3>
    {% if items.count %}
      {% for item in items.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="types: {{ item.types }}">{{ item.types }}</span> {{ item.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_item' poke.id item.id %}" method="post">
                {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{poke.name}} Already Has All Items Available</h5>
    {% endif %}
  </div>
</div>


<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  var selectEl = document.getElementById('id_region');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/pokemon/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Pokemon List</h1>

{% for poke in pokemon %}
  <a href="{% url 'detail' poke.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ poke.name }}</span>
            <p>Breed: {{ poke.breed }}</p>
            <p>Description: {{ poke.description }}</p>
            {% if poke.age > 0 %}
                <p>Age: {{ poke.age }}</p>
            {% else %}
                <p>Age: Newborn</p>
            {% endif %}
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}